### ISSUE TITLE
Remove paid content

### ISSUE THREAD

**Issue by shadowmint** [RyanNielson/awesome-unity#16]
The unity asset store already provides a comprehensive rating system for paid content.

There's no need to pull selected paid into this list; as with all the other 'Awesome Foo' repositories, consider listing only free content that can immediately be pulled into a project without restriction.

(Which is not to say, for example, that NGui isn't awesome, but once you start including paid content, the list turns into an advertising forum instead of a gamedev resource helper)

**Comment by RyanNielson** [comment]
Hmm, this is a good point. I'd be pretty curious about everyone else's opinion on the matter. The only issue I see is with lists like awesome-ruby basically all packages/gems are free and open source. Unfortunately this is not the case with Unity. But, maybe, it may spur people to make more OpenSource Unity projects.

**Comment by RyanNielson** [comment]
I got some feedback from folks on IRC. A pretty common opinion is that there's nothing wrong with some paid resources if they're tightly curated.

I think I may do two things:

1) Change the default to tagging paid resources as (Paid) and removing the tag from free resources. This should show the list's emphasis on free resources.
2) Focus the list on great free resources with some paid sprinkled in if they're really good. I don't think it's fair to remove great packages like Shader Forge just because they cost money.

How does that sound?

**Comment by shadowmint** [comment]
Sounds great to me~
